language: c

os:
  - linux
  - osx

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

sudo: required

dist: trusty # Ubuntu 14.04.

compiler:
  - gcc

install: ./.install-$TRAVIS_OS_NAME-deps.sh

addons:
  apt:
    # Travis whitelist of packages.
    # https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
    packages:
      - cmake
      - gcc
      - gfortran

script: 
  - mkdir build && cd build 
  - cmake ../ -DCMAKE_C_COMPILER=`which mpicc` -DCMAKE_CXX_COMPILER=`which mpicxx` -DCMAKE_Fortran_COMPILER=`which mpif90`
  - make VERBOSE=1
  - mpiexec -n 2 ./src/HelloWorld

